---
- name: Create credential input sources
  awx.awx.credential_input_source:
    target_credential: "{{ lookup('env', 'NAME') }}"
    source_credential: "{{ item.source_credential }}"
    input_field_name: "{{ item.input_field_name }}"
    metadata: "{{ item.metadata | to_json }}"
    state: "{{ lookup('env', 'STATE') | default('present', true) }}"
  loop: "{{ lookup('env', 'INPUT_SOURCES') | from_json }}"
  loop_control:
    label: "{{ item.source_credential }} -> {{ item.input_field_name }}"
