apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredentialType
metadata:
  name: beer-api
  namespace: awx-resource-operator
spec:
  name: Beer API
  description: Credential type for the Beer API
  kind: cloud
  connection_secret: awx-access
  inputs:
    fields:
      - id: api_token
        type: string
        label: API token
        secret: true
        required: true
  injectors:
    env:
      BEER_API_TOKEN: "{{ api_token }}"
