apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: deploy-jobtemplate
spec:
  connection_secret: awxaccess
  name: Deploy Application
  project: Demo Project
  playbook: deploy.yml
  inventory: all-environments
  extra_vars:
    application_name: order-service
    environment: uat
    release_version: "1.0.0"
  ask_limit_on_launch: true
