---
- name: Apply NetworkPolicies
  include_role:
    name: networkpolicy

- name: Read AnsibleInventory info
  kubernetes.core.k8s_info:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleInventory
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: resource_info

- name: End play early when runner job already finished
  meta: end_play
  when:
    - resource_info.resources[0].status.isFinished is defined
    - resource_info.resources[0].status.isFinished

- name: Check existing runner job
  kubernetes.core.k8s_info:
    kind: Job
    api_version: batch/v1
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: k8s_job

- name: End play early when runner job is already active
  meta: end_play
  when:
    - k8s_job.resources is defined
    - k8s_job.resources | length > 0
    - state | default('present') != 'absent'

- name: Set runner image
  set_fact:
    _runner_image: "{{ (runner_image + ':' + runner_version) if runner_image is defined and runner_version is defined else lookup('env', 'RELATED_IMAGE_ANSIBLE_JOB_RUNNER_IMAGE') }}"
    _runner_pull_policy: "{{ runner_pull_policy | default('IfNotPresent') }}"

- name: Create runner service account and job
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item) }}"
  loop:
    - service_account.yml.j2
    - job_definition.yml.j2

- name: Update AnsibleInventory status with runner job info
  operator_sdk.util.k8s_status:
    api_version: tower.ansible.com/v1alpha1
    kind: AnsibleInventory
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      k8sJob:
        created: true
        namespacedName: "{{ ansible_operator_meta.namespace + '/' + ansible_operator_meta.name }}"
        message: "AWX Inventory operation submitted to the job runner"
