apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: adak8s-domain-cert
  namespace: awx
spec:
  name: adak8s-domain-cert
  organization: Default
  connection_secret: awxaccess
  type: adak8s-domain-cert
  input_sources:
    - source_credential: Hashivault Kv:dbs-enaas-adak8s
      input_field_name: adak8s_domain_cert
      metadata:
        auth_path: approle
        secret_key: cert
        secret_path: data/adak8s/caas/k8s-sp-uat-dbs-corp_249985
        secret_backend: kv-app/sysgen
