---
galaxy_info:
  author: Ansible
  description: Credential type role for creating custom AWX credential types.
  license: MIT
  min_ansible_version: '2.9'
dependencies: []
collections:
  - operator_sdk.util
  - kubernetes.core
  - awx.awx
