---

name: AWX Integration

on:
  pull_request:
    branches: [dev]

  push:
    branches: [dev]

env:
  GO_VERSION: "1.17"
  OPERATOR_IMAGE: "quay.io/ansible/awx-resource-operator:ci"
  RUNNER_IMAGE: "quay.io/ansible/awx-resource-runner:latest"
  TOKEN_IMAGE: "quay.io/ansible/token-playbook:latest"

jobs:
  operator-image-build:
    runs-on: ubuntu-latest
    name: operator-image-build
    steps:
      - uses: actions/checkout@v3

      - name: Build operator container
        run: podman build -t ${{ env.OPERATOR_IMAGE }} .

      - name: archive operator image
        run: podman save ${OPERATOR_IMAGE} > operator.tar

      - name: upload operator image
        uses: actions/upload-artifact@v4
        with:
          name: operator.tar
          path: operator.tar

  runner-image-build:
    runs-on: ubuntu-latest
    name: runner-image-build
    steps:
      - uses: actions/checkout@v3

      - name: Build runner container
        run: podman build -f Dockerfile.runner -t ${{ env.RUNNER_IMAGE }}

      - name: archive runner image
        run: podman save ${RUNNER_IMAGE} > runner.tar

      - name: upload runner image
        uses: actions/upload-artifact@v4
        with:
          name: runner.tar
          path: runner.tar

  token-image-build:
    runs-on: ubuntu-latest
    name: token-image-build
    steps:
      - uses: actions/checkout@v3

      - name: Build token generator
        run: cd test-e2e/token-container && podman build . --tag ${{ env.TOKEN_IMAGE }}

      - name: archive token image
        run: podman save ${TOKEN_IMAGE} > token.tar

      - name: upload token image
        uses: actions/upload-artifact@v4
        with:
          name: token.tar
          path: token.tar
